config/routes.rb
Rails.application.routes.draw do
  root "landing_page#show"

  resources :users, only: %i[ show edit update destroy ] do
    scope module: :users do
      resource :role, only: :update
      resources :email_addresses, param: :token, only: %i[ new create ] do
        resource :confirmation, only: %i[ show create ], module: :email_addresses
      end
    end
  end
  resources :retros do
    scope module: :retros do
      resource :waiting_room, only: :show
      resource :action_review, only: :show
      resource :brainstorming, only: :show
      resource :grouping, only: :show
      resource :voting, only: :show
      resource :discussion, only: :show
      resource :discussion_item, only: :update
      resource :complete, only: :show
      resource :export, only: :show
      resource :start, only: :create
      resource :action_review_selection, only: :create
      resource :finished, only: :update
      resource :finish_brainstorming, only: :create
      resource :phase_transition, only: :create
      resource :phase_back, only: :create
      resources :feedback_groups, only: %i[create destroy] do
        delete :remove_feedback, on: :collection
      end
      resources :votes, only: %i[create destroy]
      resource :highlight, only: %i[update destroy]
      resource :music, only: :update
      resource :jira_export, only: :create
    end
    resources :feedbacks, only: %i[ new create show edit update destroy ] do
      resource :publish, only: :create, module: :feedbacks
    end
    resources :actions, only: %i[ new create show edit update destroy ] do
      resource :publish, only: :create, module: :actions
      resource :completion, only: :update, module: :actions
    end
  end

  # Account settings
  namespace :account do
    resource :join_code, only: %i[ show edit update destroy ]
    resource :settings, only: %i[ show update ]
    resource :subscription, only: %i[ show create ]
    resource :billing_portal, only: :show
    resource :jira_integration, only: %i[ show create update destroy ]
  end

  # Join codes for multi-account
  get "join/:code", to: "join_codes#new", as: :join
  post "join/:code", to: "join_codes#create"

  # Retro invite links (combines join code + retro access)
  get "invite/:code/retro/:retro_id", to: "retros/invites#show", as: :retro_invite
  post "invite/:code/retro/:retro_id", to: "retros/invites#create"

  # User verifications
  namespace :users do
    resources :verifications, only: %i[ new create ]
  end

  # Session management with magic links
  resource :session do
    scope module: :sessions do
      resources :transfers
      resource :magic_link do
        post :resend, on: :member
      end
      resource :menu
    end
  end

  get "/signup", to: redirect("/signup/new")
  get "/landing_page", to: redirect("/")

  # Signup flow
  resource :signup, only: %i[ new create ] do
    collection do
      scope module: :signups, as: :signup do
        resource :completion, only: %i[ new create ]
      end
    end
  end

  # Tenanted entry point (after account switch)
  resource :landing, only: :show

  # My namespace for nav menu and user-specific resources
  namespace :my do
    resource :menu
  end

  # Site feedback (app feedback from users)
  resource :site_feedback, only: %i[new create]

  # Health check
  get "up", to: "rails/health#show", as: :rails_health_check

  # SEO
  get "sitemap.xml", to: "sitemaps#show", as: :sitemap, defaults: { format: :xml }
  get "favicon.ico", to: redirect("/icon.png")

  # Legal pages
  get "imprint", to: "legal#imprint", as: :imprint
  get "privacy_policy", to: "legal#privacy_policy", as: :privacy_policy
  get "privacy-policy", to: redirect("/privacy_policy")
  get "privacy", to: redirect("/privacy_policy")

  # Blog
  get "blog", to: "blog#index", as: :blog
  get "blog/:id", to: "blog#show", as: :blog_post
  get "shoutouts", to: "shoutouts#index", as: :shoutouts

  # Alternative pages (SEO)
  get "alternative/easyretro", to: "alternatives#easyretro", as: :alternative_easyretro
  get "alternative/parabol", to: "alternatives#parabol", as: :alternative_parabol
  get "alternative/metroretro", to: "alternatives#metroretro", as: :alternative_metroretro
  get "alternative/teamretro", to: "alternatives#teamretro", as: :alternative_teamretro
  get "retro/create", to: redirect("/retros/new")

  # Admin
  namespace :admin do
    resource :stats, only: :show
    resource :test_exception, only: :create
  end

  # Stripe webhooks
  post "stripe/webhooks", to: "stripe/webhooks#create"

  # Catch-all route for unmatched paths (must be last)
  match "*unmatched", to: "errors#not_found", via: :all
end

app/controllers/sitemaps_controller.rb
class SitemapsController < ApplicationController
  disallow_account_scope
  allow_unauthenticated_access
  layout false

  def show
    @posts = BlogPost.all rescue []

    respond_to do |format|
      format.xml
    end
  end
end

app/views/sitemaps/show.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <%# Landing Page %>
  <url>
    <loc><%= root_url(script_name: nil) %></loc>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>

  <%# Blog Index %>
  <url>
    <loc><%= blog_url(script_name: nil) %></loc>
    <changefreq>daily</changefreq>
    <priority>0.8</priority>
  </url>

  <%# Public Marketing Pages %>
  <url>
    <loc><%= shoutouts_url(script_name: nil) %></loc>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>

  <%# Blog Posts %>
  <% @posts.each do |post| %>
  <url>
    <loc><%= blog_post_url(post.slug, script_name: nil) %></loc>
    <lastmod><%= post.date.iso8601 %></lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <% end %>

  <%# Alternative Pages (SEO) %>
  <url>
    <loc><%= alternative_easyretro_url(script_name: nil) %></loc>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>

  <url>
    <loc><%= alternative_parabol_url(script_name: nil) %></loc>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>

  <url>
    <loc><%= alternative_metroretro_url(script_name: nil) %></loc>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>

  <url>
    <loc><%= alternative_teamretro_url(script_name: nil) %></loc>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>

</urlset>